version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_crud_db
      MYSQL_USER: product_crud_user
      MYSQL_PASSWORD: product_crud_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - $PWD/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: product-crud-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product_crud_db
      SPRING_DATASOURCE_USERNAME: product_crud_user
      SPRING_DATASOURCE_PASSWORD: product_crud_user

volumes:
  mysql_data: